import logging
from typing import Any
from core.blueprint import Event

logger = logging.getLogger("sab.macro_runner")


def insert_macro_stub(doc: Any, action_name: str) -> None:
    """
    Inserts a Basic macro stub into the document's Basic Standard library.
    """
    try:
        # Get or create Standard library
        if not doc.BasicLibraries.hasByName("Standard"):
            doc.BasicLibraries.createLibrary("Standard")
        
        standard_lib = doc.BasicLibraries.getByName("Standard")
        
        # Check if macro module already exists
        module_name = "SAB_AutoGenerated"
        existing_code = ""
        if standard_lib.hasByName(module_name):
            existing_code = standard_lib.getByName(module_name)
        
        # If the action stub is already in the module, skip inserting
        sub_signature = f"Sub {action_name}"
        if sub_signature in existing_code:
            logger.info(f"Macro {action_name} already exists in {module_name}.")
            return

        # Build macro code stub
        macro_stub = (
            f"\nSub {action_name}()\n"
            f"    ' Auto-generated stub for {action_name}\n"
            f"    MsgBox \"Triggered action: {action_name}. Please implement custom logic in LibreOffice macros!\"\n"
            f"End Sub\n"
        )
        
        if not existing_code:
            new_code = "REM  ##### SAB AUTO-GENERATED MACROS #####\n" + macro_stub
        else:
            new_code = existing_code + macro_stub

        if standard_lib.hasByName(module_name):
            standard_lib.replaceByName(module_name, new_code)
        else:
            standard_lib.insertByName(module_name, new_code)
            
        logger.info(f"Successfully inserted macro stub '{action_name}' into document library.")
    except Exception as e:
        logger.warning(f"Could not insert macro stub '{action_name}' into document Basic libraries: {e}")


def assign_macro_to_cell(doc: Any, sheet: Any, cell: Any, event: Event) -> None:
    """
    Wires the macro trigger to the cell. For LibreOffice Calc, we set the cell's Formula
    to use HYPERLINK referencing the macro URL, or simulate the dispatch.
    
    Macro URL in LibreOffice:
    "vnd.sun.star.script:Standard.SAB_AutoGenerated.action_name?language=Basic&location=document"
    """
    action_name = event.action
    macro_url = f"vnd.sun.star.script:Standard.SAB_AutoGenerated.{action_name}?language=Basic&location=document"
    
    # We can set the cell's Formula as a HYPERLINK formula pointing to the macro
    # This turns the cell text into a clickable link that executes the macro.
    label = cell.getString() or "Click Here"
    cell.setFormula(f'=HYPERLINK("{macro_url}"; "{label}")')
    logger.info(f"Assigned macro hyperlink {macro_url} to cell.")
